Objetivo 4
Mapachana/Predictor-COVID pull request #13
Opened 2021-11-07 22:14 UTC by Mapachana

Se implementa lo más básico de las clases Datos e Interpretación y se añaden tests para comprobar su correcto funcionamiento.

closes #10 
closes #11 
closes #12

2021-11-09 12:47 UTC, JJ requested changes
Por favor, seguid las mejores prácticas en desarrollo. Los issues plantean problemas, los mensajes de commit dicen cómo se ha solucionado. Ni #12 plantea un problema ni 18290b8 dice como se soluciona.
Adicionalmente, este PR (ni los issues correspondientes) están en ningún milestone. No se puede avanzar hacia un PMV sin enmarcar en un milestone.
Aparte de todos los comentarios hecho. Una vueltecilla y listo.

2021-11-09 12:47 UTC, JJ commented on prediccion/datos.py
> +class Datos:
Si sólo "representa", ¿por qué no es una dataclass?

2021-11-09 12:47 UTC, JJ commented on prediccion/interpretacion.py
> +        self.contenedor_datos = list(datos)
¿Y si datos es ya una lista?

2021-11-09 12:47 UTC, JJ commented on prediccion/interpretacion.py
> +    def leer_datos(self,fichero_leer):
¿Por qué no se hace esto en el constructor?

2021-11-09 12:47 UTC, JJ commented on prediccion/interpretacion.py
> +        with open(fichero_leer, "r") as fichero:
¿Qué pasa si no existe el fichero?

2021-11-09 12:47 UTC, JJ commented on prediccion/interpretacion.py
> +            num_dias = 14
Estos números:
1. Deberían ser constantes definidas
2. Deberían estar en alguna HU y/o issue

2021-11-09 12:47 UTC, JJ commented on tasks.py
> +	run("pytest tests/")
pytest no debería necesitar el directorio si es estándar.

2021-11-09 12:47 UTC, JJ commented on tests/test_interpretacion.py
> +    aux = unittest.TestCase()
En vez de hacer esto, ¿por qué no haces que este test sea una clase?

2021-11-09 12:47 UTC, JJ commented on prediccion/interpretacion.py
> +            if total_casos < 500:
Os dije en clase que NUNCA se imprime desde una rutina. Siempre se devuelven valores en un objeto que se pueda interpretar o imprimir o lo que sea.

2021-11-09 12:47 UTC, JJ commented on tests/test_interpretacion.py
> +    interp.generar_interpretacion('Andalucía', '2021-01-10')
Y no se imprime desde una rutina precisamente por eso. La lógica de negocio y toda la lógica de una aplicación no puede depender de que se capture o no una salida. ¿Qué pasa si se ejecuta en un servidor?

2021-11-09 19:38 UTC, Mapachana commented
Listo para revisión @JJ

2021-11-09 19:43 UTC, JJ requested changes
Has solucionado todos los problemas puntuales, pero sigues sin trabajar con issues que representen un problema, como te he indicado.

2021-11-09 20:41 UTC, Mapachana commented
He revisado los issues y eliminado los que se referían a tareas.
Listo para revision @JJ

2021-11-10 06:24 UTC, JJ commented
> He revisado los issues y eliminado los que se referían a tareas. Listo para revision @JJ

OK, has cambiado enlaces de commits a issues que *no* representan un problema a enlazar issues que *no* existen. No se puede decir que sea realmente una mejora. El código (y los commits correspondiente) siguen teniendo que enlazar a un issue que represente un problema, y que exista, porque si no es imposible saber por qué se han desarrollado de esa forma.

2021-11-10 07:43 UTC, Mapachana commented
Para arreglar los commits a issues que no existen, ¿cómo lo hago? ¿Puedo editar los commits de alguna manera?

2021-11-10 07:44 UTC, JJ commented
Crea issues que sigan las reglas, y arregla el código que solucione los problemas referenciados por esos commits. Tienes que asumir que si se ha hecho sin ningún issue, o con issues incorrectos, el código está mal.

2021-11-10 08:04 UTC, Mapachana commented
Aunque cree issues nuevos si no cambio los commits habrá commits que sigan referenciando issues inexistentes, ¿no pasa nada por eso?

2021-11-10 08:06 UTC, JJ commented
Hombre, pasar lo que se dice pasar no pasa nada si los últimos commits referencian issues que existan y que representen un problema. Pero lo que pasa es que este tipo de prácticas no se consideran buenas prácticas, en general, así que mejor no hacerlas.

2021-11-10 10:58 UTC, JJ requested changes
Supongo que no estaba todavía listo para revisión, pero en todo caso, cuando lo hagas, por favor ten en cuenta todos, o al menos la mayoría, de los problemas que hay. Ánimo, ya queda menos.

2021-11-10 10:58 UTC, JJ commented on tests/test_interpretacion.py
> +        Metodo test para comprobar si el contenedor de datos esta vacio
typo

2021-11-10 10:58 UTC, JJ commented on tests/test_interpretacion.py
> +        Metodo que crea el objeto interpretacion a usar para los tests
Las funciones de tests deberían ser autodocumentadas (con el nombre, por ejemplo)

2021-11-10 10:58 UTC, JJ commented on prediccion/datos.py
> +from dataclasses import dataclass
Buenas prácticas: los datos no pueden ir en el mismo directorio que el código (lo digo por la de arriba)

2021-11-10 10:58 UTC, JJ commented on prediccion/interpretacion.py
> +            sys.exit("El archivo no existe")
No puedes hacer esto; tienes que levantar una excepción específica.

2021-11-10 10:58 UTC, JJ commented on prediccion/interpretacion.py
> +                casos = int(aux[3])+int(aux[4])+int(aux[5])+int(aux[6])+int(aux[7])+int(aux[7])
¿map-reduce?

2021-11-10 10:58 UTC, JJ commented on requirements-dev.txt
> +pylint==2.4.4
También os dije que la buena práctica actual es usar pyproject.toml para especificar metadatos y dependencias.

2021-11-10 10:59 UTC, Mapachana commented
He hecho commits nuevos para que los últimos commits de los ficheros correspondientes no referencien a issues que no existen.

No he creado nuevas issues porque los tests no requieren crear un issue para ellos, y no considero que haya problemas que documentar ahora mismo salvo los dos que ya existían de antes y ya están referenciados en commits y PR.

2021-11-10 10:59 UTC, Mapachana commented
Listo para revision @JJ

2021-11-10 11:02 UTC, Mapachana commented on prediccion/interpretacion.py
> +            sys.exit("El archivo no existe")
pero entonces el programa se interrumpe igual que si se levanta un FileNotFoundError no?

2021-11-10 11:09 UTC, JJ commented on prediccion/interpretacion.py
> +            sys.exit("El archivo no existe")
¿Qué programa se va a interrumpir? No hay ningún programa. Ni siquiera lo tienes en tus milestones.

2021-11-10 11:11 UTC, JJ commented
> He hecho commits nuevos para que los últimos commits de los ficheros correspondientes no referencien a issues que no existen.
> 
> No he creado nuevas issues porque los tests no requieren crear un issue para ellos, y no considero que haya problemas que documentar ahora mismo salvo los dos que ya existían de antes y ya están referenciados en commits y PR.

*El código* requiere un issue que represente un problema para poder hacerse correctamente. Y ya te he dicho esto antes. No se trata de "documentar" problemas. Se trata de plantear la implementación de las HUs como un problema (issue) que se resuelve con el código (y en el mensaje de commit se comenta cómo se ha resuelto y qué decisiones de han tomado)

2021-11-10 11:11 UTC, JJ commented
Tampoco has documentado las decisiones que has tomado sobre *test runner* y bibliotecas de aserciones.

2021-11-10 11:12 UTC, JJ commented
> Crea issues que sigan las reglas, y arregla el código que solucione los problemas referenciados por esos commits. Tienes que asumir que si se ha hecho sin ningún issue, o con issues incorrectos, el código está mal.

:point_up:

2021-11-10 11:52 UTC, Mapachana commented on prediccion/interpretacion.py
> +            sys.exit("El archivo no existe")
Es decir, al levantar una excepcion propia el programa se interrumpe igual que si no se gestionara el FileNotFoundError, ¿Para qué sirve gestioanrlo entonces?

2021-11-10 14:14 UTC, Mapachana commented
Listo para revision @JJ

2021-11-11 06:23 UTC, JJ approved these changes
El objetivo está superado, pero hay una serie de temas que convendría mejorar antes del siguiente objetivo.

2021-11-11 06:23 UTC, JJ commented on docs/objetivo4.md
> +Respecto al testrunner, se consideraron como opciones `pytest` y `unittest`.
unittest no es un test runner. ¿unittest es un comando que ejecuta los tests?

2021-11-11 06:23 UTC, JJ commented on docs/objetivo4.md
> +`Pytest` es mucho más sencillo y fácil de usar, pero finalmente se ha usado `unittest`, ya que pese a que necesita declarar una clase hija de `unittest.TestCase` ofrece una forma sencilla de comproba
Pytest solo tiene una aserción, y también "raises". unittest es una biblioteca de aserciones con una serie de órdenes y clases. No son ni siquiera comparables.

2021-11-11 06:23 UTC, JJ commented on prediccion/interpretacion.py
> +        self.num_dias = 14
Si no vas a variarlo, debería ser una "constante"

2021-11-11 06:23 UTC, JJ commented on prediccion/interpretacion.py
> +            if self.contenedor_datos[i].com_autonoma == com_auto and self.contenedor_datos[i].fecha == fecha:
Este tipo de bucles evidencia que la estructura de datos que debes usar para almacenar debe ser otra que permita acceso indexado por ambos índices. Un diccionario (con clave comunidad autónoma) de un diccionario (con clave fecha)

2021-11-11 06:23 UTC, JJ commented on prediccion/interpretacion.py
> +                total_casos = total_casos + self.contenedor_datos[i].num_casos
También podías usar reduce, pero la cuestión es que tienes que mirar cómo, cuando y cuanto vas a acceder a cada dato para hacer más rápido su cálculo. Si cada día añades los casos al total, puedes tenerlo almacenado en algún lado.
(En realidad la serie cambia en días anteriores cada cierto tiempo, así que no sería tan simple)

2021-11-11 06:23 UTC, JJ commented on prediccion/interpretacion.py
> +                return "Vamos bien"
Devolver cadenas nunca es una buena práctica; deberías usar ENUMs

2021-11-11 09:14 UTC, merged