[IV-21-22] Objetivo 6
Mapachana/Predictor-COVID pull request #22
Opened 2021-12-12 19:32 UTC by Mapachana

* [X]  ¿Se han configurado varios sistemas de integración continua?
* [X]  ¿Se ha configurado correctamente el *Checks API* en los sistemas en los que
   sea necesario para que aparezca correctamente en GitHub (y se pueda comprobar
   desde los tests)?
* [X]  ¿Uno de los sistemas configurados permite comprobar cuales son las versiones
   del lenguaje con las que funciona correctamente nuestra aplicación?
* [X]  ¿Se escogen de forma adecuada las versiones del lenguaje que se testean,
   tanto en el sistema de CI como en el contenedor Docker?

2021-12-12 19:45 UTC, Mapachana commented
Los revisores aleatorios han sido @lentes4k @paula1999 @modejota

2021-12-12 21:30 UTC, modejota commented on .github/workflows/test_docker.yaml
> +
No entiendo muy bien para qué construir el contenedor y publicarlo dos veces, una en cada workflow. 
A mi parecer, uno debería ser exclusivamente para construirlo y publicarlo, si se cumplen requisitos, y el otro para testear, descargando el contenedor.

2021-12-12 21:31 UTC, modejota commented on .github/workflows/deploy_docker.yaml
> -
IMO, sí que lo dejaría en push. Sólo que utilizaría la subopción "paths" para que solo se reconstruya cuando se necesite, es decir, cuando cambien ficheros como el Dockerfile, Readme.md o el de dependencias

2021-12-12 22:08 UTC, Mapachana commented on .github/workflows/test_docker.yaml
> +
Porque son contenedores docker distintos. El contenedor del workflow que solo lo publica es del objetivo anterior, y usa  python 3.8 .
El contenedor que ademas lanza los tests (test-docker.yaml) usa python 10 e instala dependencias especificas de poetry.
Por eso publico dos contenedores, porque no son el mismo

2021-12-12 22:15 UTC, modejota commented on .github/workflows/test_docker.yaml
> +
Entonces, si el contenedor de Python 3.8 no se utiliza para ejecutar test en las GHAction, y por lo que veo, tampoco en CircleCI, ¿cual es la finalidad de su existencia?

2021-12-12 22:31 UTC, Mapachana commented on .github/workflows/test_docker.yaml
> +
El contenedor de python 3.8 es del objetivo anterior, se puede usar para pasar los tests pero no lo he implementado. Se usa localmente llamando a la orden de invoke para hacer los tests

2021-12-12 22:35 UTC, Mapachana commented on .github/workflows/test_docker.yaml
> +
Pensandolo ahora que lo dices tendria sentido tener otra github action aparte para que lance los tests, one sec y añado los cambios

2021-12-12 22:41 UTC, modejota commented on .github/workflows/test_docker.yaml
> +
Leyendo la documentación dices que 3.8 ya lo testeaste en objetivo anterior, pero, si añades dependencias nuevas requerirá testeo otra vez. Si el único que no puedes testear en CircleCI es el 3.10 por lo que comentas de poetry (que conste no soy experto en Python), haz el contenedor para los test del 3.10 "a mano" en la GHAction, y testea con CircleCI las otras versiones que no dan problemas, 3.[7,8,9]. O por lo menos, es lo que yo haría.

2021-12-12 22:57 UTC, Mapachana commented
Ya debería estar listo @modejota

2021-12-12 23:30 UTC, Mapachana commented on .github/workflows/test_docker.yaml
> +
Tienes razon, he añadido en el ultimo commit una github action para testear el contenedor del objetivo anterior (3.8).
Como comentas, es la unica solucion a la que he llegado, las versiones 3.7 y 3.9 las testeo en circleci.
Las versiones 3.8 y 3.10 las testeo con docker cada una en su github action :D

2021-12-13 12:37 UTC, paula1999 commented on .github/workflows/test_docker.yaml
> +
Es un poco lío que haya varios archivos y cada uno trabaje con una o varias versiones. Es decir, no veo necesario que subas y testees la versión 3.8, aparte subas y testees la versión 3.10 y en otro sitio testees las versiones 3.7 y 3.9. Pienso que deberías eliminar el archivo que testea la versión 3.8 (`test_docker.yaml`) e incluir en la matrix del archivo `.circleci/config.yml` dicha versión. De esta forma, queda más claro que subes un contenedor con la versión 3.8 de python y lo testeas con las versiones 3.7 al 3.9 (en un mismo archivo) y como la versión 3.10 no puedes incluirla, pues veo correcto que necesites hacer lanzar una Github Action para esta versión.

2021-12-13 12:56 UTC, modejota commented on .github/workflows/test_docker.yaml
> +
Básicamente lo que venía diciendo yo ayer. CircleCI para las versiones que no dan problemas, 3.7 3.8 y 3.9 (y probablemente ni siquiera necesites testear las 3) y la GH Action con el contenedor Docker para la problemática, la 3.10. 

Era bastante lío trabajar con las versiones así de forma separada, y tener scripts prácticamente iguales.

2021-12-13 13:56 UTC, modejota commented on .github/workflows/deploy_and_test_docker.yaml
> +    paths:
Lo tendría que haber aclarado en el otro comentario, mea culpa. Si lo haces así, sólo ejecutará los test cuando modifiques alguno de esos ficheros, lo cual seguramente no es el comportamiento deseado. La solución, hasta donde sé, pasa por dos caminos, especificar dos jobs secuenciales (de manera que los test se ejecuten siempre, pero después de reconstruir, de ser necesario esto) oooo, vuelves a la versión en que solo tenias "on push"

2021-12-13 15:01 UTC, lentes4k commented on .github/workflows/test_docker.yaml
> +
Me uno a esta discusión. Esta claro que te has pegado un pedazo de curre (por lo que se puede ver tanto por aquí como lo que te he visto en clase). Quizás te hubiera ahorrado muchos problemas el haber investigado la matrix de las GH Actions ya que esta si que te permite usar python 3.10 y no tener que replicar el Dockerfile y el código que te hace lanzar los tests en esta versión. Ya que como el profe nos dice JJ y podemos observar en otros proyectos no estas siguiendo las buenas prácticas.
En mi opinión, y tras el currazo lo dejaría así a pesar de que "manche" un poco la estética del proyecto ya que es funcional y resuelve lo que se pedía en el objetivo

2021-12-13 17:43 UTC, Mapachana commented on .github/workflows/test_docker.yaml
> +
@lentes4k no he usado una matrix porque los contenedores no son analogos, en python 3.10 por movidas varias de poetry que estáne n la documentacion adicional (le falta modulos) los instalo a mano. Y en pytest tambie. Por eso son contenedores docker distintos, no puedo solamente crear un argumento que sea la version de python y ya  (ojalá porque me habría ahorrado muchos problemas)

2021-12-13 17:45 UTC, Mapachana commented on .github/workflows/deploy_and_test_docker.yaml
> +    paths:
Es verdad, no caí yo tampoco. Como al final voy a probar a poner la python 3.8 en circleci no importa, pero llevas razón, gracias!

2021-12-13 17:50 UTC, Mapachana commented on .circleci/config.yml
> +        - run: pyenv install -v << parameters.version >>; pyenv global << parameters.version >>; pip install invoke; pip install cleo importlib_metadata;  wget -q -O - "$@" https://raw.githubusercont
Está puesto así por tema de eficiencia. es mas rapido mandar un solo comando largo que varios cortos. Miré que circleci daba una sintaxis para separar comandos en varias lineas usando un mismo run, pero la sintaxis me parecía poco intuitiva

2021-12-13 18:08 UTC, Mapachana commented
- He quitado el github action para testear el python 3.8 y lo he añadido a la matrix de circleci como habéis indicado los tres
- He separado la github action del python 3.10 de forma que una es para subir la imagen y la otra para pasar los tests (así evito el problema de que se suba siempre o de que los tests no pasen siempre que mencionó @modejota )
- He dejado la github action para subir el dockerfile con python 3.8 porque es del objetivo 5 y no estorba

ya están todos los cambios @paula1999 @modejota @lentes4k

2021-12-13 18:29 UTC, modejota commented
Okey, por mi parte diría que ya está todo.

2021-12-13 18:31 UTC, lentes4k commented
Yo también lo veo chévere así

2021-12-13 20:12 UTC, paula1999 approved these changes
👍

2021-12-13 21:12 UTC, modejota approved these changes

2021-12-13 22:22 UTC, Mapachana commented
Listo para revisión @JJ

2021-12-14 08:32 UTC, lentes4k approved these changes

2021-12-15 22:45 UTC, Mapachana commented on .circleci/config.yml
> +        - run: pyenv install -v << parameters.version >>; pyenv global << parameters.version >>; pip install invoke; pip install cleo importlib_metadata;  wget -q -O - "$@" https://raw.githubusercont
No sabía que en yaml se podía hacer eso, gracias!

2021-12-16 11:45 UTC, JJ requested changes
Buen trabajo por parte de todo el mundo, pero convendría que hicieras caso a algunas de las cosas que han comentado.

2021-12-16 11:45 UTC, JJ commented on .github/workflows/test_docker.yaml
> +      - name: Lanzar Tests
Aquí o estás lanzando el test pocas veces (porque no lo haces con los PRs) o estás construyendo el Dockerfile demasiadas. Creo que tendrías que hacerle caso a los de arriba...

2021-12-16 11:46 UTC, JJ commented on .github/workflows/test_docker.yaml
> +
Quita también los comentarios que muestran que se ha usado el generador de GHAs

2021-12-16 11:54 UTC, Mapachana commented on .github/workflows/test_docker.yaml
> +      - name: Lanzar Tests
El contenedor docker solo se construye al modificar los ficheros de dependencias o de tares o el propio dockerfile. Como me lo dijeron mis compañeros, lo separé en dos github actions, la deploy_docker_3.10 que se encarga de reconstruir y subir la imagen. Esa github action solo lanza los tests. Voy a añadir que los ejecute en los pr. Gracias!

2021-12-16 12:24 UTC, Mapachana commented
Vale creo que parecía que subía el contenedor docker más veces a dockerhub de lo que lo hacía porque se me había pasado cambiar los nombres de los workflows. 
El contenedor docker como bien apuntaron mis compañeros solo se reconstruye al cambiar dependencias, tasks.py o el contenedor propiamente.
Mientras los tests se lanzan siempre (al hacer push a main o pull request a main). Lo he puesto así porque si ponia en push y pr en general se lanzaban dos veces y no era necesario.

2021-12-16 12:25 UTC, Mapachana commented
Listo para revisión @JJ

2021-12-16 16:30 UTC, JJ approved these changes
Lo que queda es principalmente de detalle. Buen trabajo por parte de todo el mundo pero sobre todo @Mapachana , claro.

2021-12-16 16:30 UTC, JJ commented on .circleci/config.yml
> +        - run: pyenv install -v << parameters.version >>; pyenv global << parameters.version >>; pip install invoke; pip install cleo importlib_metadata;  wget -q -O - "$@" https://raw.githubusercont
... ¿Alguna razón para no hacerlo?
Also: quita comentarios.

2021-12-16 16:30 UTC, JJ commented on .github/workflows/test_docker.yaml
> +      - name: Install Docker
docker está instalado en todos los runners.

2021-12-16 16:30 UTC, JJ commented on .github/workflows/test_docker.yaml
> +      - name: Log in to Docker Hub
Normalmente si haces pocos pulls al día no tienes por qué hacer login.

2021-12-16 23:16 UTC, merged